name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: 3.x

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run Tests
      working-directory: ./build
      run: ./tests

    - name: Run Valgrind
      uses: steinwurf/valgrind-action@5.1.0
      continue-on-error: true
      with:
        program: ./build/tests

    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: ./build

