name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: lukka/get-cmake@latest
      with:
        cmake-version: 3.x

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make
        sudo apt-get update -y && sudo apt-get install -y valgrind

    - name: Run Tests
      working-directory: ./build
      run: ./tests

    - name: Run Valgrind
      working-directory: ./build
      run: |
        valgrind --leak-check=full --show-leak-kinds=all ./tests
      continue-on-error: true
